apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-chart.fullname" . }}
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: metrics-port
      protocol: TCP
      name: http
  selector:
    {{- include "example-chart.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-chart.fullname" . }}-cluster-service
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8888
      targetPort: metrics-port
      protocol: TCP
      name: http
  selector:
    {{- include "example-chart.selectorLabels" . | nindent 4 }}